name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))) ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Detect target branch
        id: detect-branch
        run: |
          # デフォルトは develop
          TARGET_BRANCH="develop"

          if [[ "${{ github.event_name }}" == "issue_comment" || \
                "${{ github.event_name }}" == "pull_request_review_comment" || \
                "${{ github.event_name }}" == "pull_request_review" || \
                "${{ github.event_name }}" == "issues" ]]; then
            BODY="${{ github.event.comment.body || github.event.review.body || github.event.issue.body }}"
            echo "Comment/Issue body: $BODY"

            # 最初に出てきた「〇〇ブランチ」を抽出
            if [[ "$BODY" =~ ([a-zA-Z0-9._/-]+)ブランチ ]]; then
              TARGET_BRANCH="${BASH_REMATCH[1]}"
            fi
          else
            # push/PR の場合は従来通り
            TARGET_BRANCH="${{ github.event.pull_request.head.ref || github.ref_name }}"
          fi

          echo "Target branch resolved: $TARGET_BRANCH"
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Display context information
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Target branch: $TARGET_BRANCH"
          echo "Base branch: ${{ github.event.pull_request.base.ref || 'N/A' }}"

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          prompt: |
            You are helping with the BusSchedules project.

            Context:
            - Repository: ${{ github.repository }}
            - Target branch: ${{ env.TARGET_BRANCH }}
            - Event type: ${{ github.event_name }}
            - Base branch: ${{ github.event.pull_request.base.ref || 'N/A' }}
            - Comment/Issue content: "${{ github.event.comment.body || github.event.review.body || github.event.issue.body }}"

            Please provide constructive and helpful feedback.

          claude_args: '--model claude-opus-4-1-20250805 --allowed-tools Bash(git:*),Bash(gh:*),View,GlobTool,GrepTool,Write'
